import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// ...existing code...
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="relative min-h-screen">
        {/* Fondo turístico */}
        <div className="fixed inset-0 -z-10">
          <img
            src="/turismo-bg.jpg"
            alt="Fondo turístico"
            className="w-full h-full object-cover"
          />
          {/* Overlay de color en tendencia */}
          <div className="absolute inset-0 bg-gradient-to-br from-blue-600/60 via-purple-500/40 to-pink-400/30" />
        </div>
        {children}
      </body>
    </html>
  );
}
// ...existing code...