import type { Metadata } from "next";
import "./globals.css";
import NextImageBg from "./_components/NextImageBg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="relative min-h-screen">
        {/* Fondo turístico optimizado con Next.js Image */}
        <div className="fixed inset-0 -z-10">
          <NextImageBg />
          {/* Overlay de color en tendencia */}
          <div className="absolute inset-0 bg-gradient-to-br from-blue-600/60 via-purple-500/40 to-pink-400/30" />
        </div>
        {children}
      </body>
    </html>
  );
}